"""
Django settings for ResearchMate project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os


def refresh_settings_from_env():
    global GROQ_API_KEY, GROQ_MODEL, AI_PROVIDER
    GROQ_API_KEY = os.environ.get('GROQ_API_KEY')
    GROQ_MODEL = os.environ.get('GROQ_MODEL', 'openai/gpt-oss-120b')
    AI_PROVIDER = os.getenv('AI_PROVIDER', 'groq')


def load_env_file(env_file=None):
    """Load Groq-related values from the local .env file without relying on a stale process environment."""
    resolved_env_file = Path(env_file) if env_file is not None else BASE_DIR / '.env'
    if not resolved_env_file.exists():
        refresh_settings_from_env()
        return False

    try:
        for raw in resolved_env_file.read_text(encoding='utf8').splitlines():
            line = raw.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            key, val = line.split('=', 1)
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            sslcommerz_keys = {'SSLCOMMERZ_STORE_ID', 'SSLCOMMERZ_STORE_PASSWORD', 'SSLCOMMERZ_SANDBOX', 'SSLCOMMERZ_SUCCESS_URL', 'SSLCOMMERZ_FAIL_URL', 'SSLCOMMERZ_CANCEL_URL'}
            if key in {'GROQ_API_KEY', 'GROQ_MODEL', 'AI_PROVIDER'} | sslcommerz_keys or key not in os.environ:
                os.environ[key] = val
    except Exception:
        refresh_settings_from_env()
        return False

    refresh_settings_from_env()
    return True


# Load simple .env file if present (KEY=VALUE lines). This avoids adding new
# dependencies while allowing local API keys to be set for development.
# For project-specific settings like the Groq key, prefer the local .env file so
# a stale OS environment variable cannot keep sending an old key after updates.
load_env_file()

# Expose Groq settings in settings for easy access by services.
refresh_settings_from_env()


# SSLCOMMERZ payment gateway configuration (development / sandbox).
# Credentials are read from the environment / local .env file and are never
# hardcoded. Real payment verification happens server-side in a later phase.
SSLCOMMERZ_STORE_ID = os.environ.get('SSLCOMMERZ_STORE_ID', '')
SSLCOMMERZ_STORE_PASSWORD = os.environ.get('SSLCOMMERZ_STORE_PASSWORD', '')
SSLCOMMERZ_SANDBOX = os.environ.get('SSLCOMMERZ_SANDBOX', 'True').strip().lower() in ('1', 'true', 'yes', 'on')
SSLCOMMERZ_SUCCESS_URL = os.environ.get(
    'SSLCOMMERZ_SUCCESS_URL', 'http://localhost:8000/subscriptions/payment/success/'
)
SSLCOMMERZ_FAIL_URL = os.environ.get(
    'SSLCOMMERZ_FAIL_URL', 'http://localhost:8000/subscriptions/payment/fail/'
)
SSLCOMMERZ_CANCEL_URL = os.environ.get(
    'SSLCOMMERZ_CANCEL_URL', 'http://localhost:8000/subscriptions/payment/cancel/'
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y2%f+cwp#vnnz@7g&eb64lc1lwu@84_u5)mi329pp21$^xh=7o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0', 'testserver']

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'papers',
    'subscriptions',
    'admin_panel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ResearchMate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ResearchMate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

