# Generated by Django 6.0.7 on 2026-07-26 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Uploaded', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
