# Generated by Django 6.0.7 on 2026-07-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extraction_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='papers.paper')),
            ],
        ),
    ]
