# Generated by Django 6.0.7 on 2026-07-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_papercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('beginner_explanation', models.TextField(blank=True)),
                ('technical_explanation', models.TextField(blank=True)),
                ('key_contributions', models.TextField(blank=True)),
                ('key_concepts', models.JSONField(blank=True, default=list)),
                ('reading_difficulty_level', models.CharField(blank=True, max_length=50)),
                ('reading_difficulty_reason', models.TextField(blank=True)),
                ('analysis_status', models.CharField(blank=True, default='Pending', max_length=30)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='papers.paper')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('simple_explanation', models.TextField(blank=True)),
                ('technical_explanation', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='papers.paper')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_completed', models.BooleanField(default=False)),
                ('beginner_completed', models.BooleanField(default=False)),
                ('technical_completed', models.BooleanField(default=False)),
                ('glossary_completed', models.BooleanField(default=False)),
                ('flashcards_completed', models.BooleanField(default=False)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('viva_completed', models.BooleanField(default=False)),
                ('notes_completed', models.BooleanField(default=False)),
                ('overall_progress', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='papers.paper')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VivaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('suggested_answer', models.TextField(blank=True)),
                ('follow_up_question', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_questions', to='papers.paper')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
