# Generated by Django 6.0.7 on 2026-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_aianalysis_flashcard_glossary_learningprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='analysis_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['paper', 'display_order'], name='papers_flas_paper_i_b0c079_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['paper'], name='papers_lear_paper_i_01a8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['paper', 'display_order'], name='papers_quiz_paper_i_e30304_idx'),
        ),
        migrations.AddIndex(
            model_name='vivaquestion',
            index=models.Index(fields=['paper', 'display_order'], name='papers_viva_paper_i_de1d4e_idx'),
        ),
    ]
