# Generated by Django 6.0.7 on 2026-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_aianalysis_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='raw_response',
            field=models.TextField(blank=True),
        ),
    ]
