# Generated by Django 6.0.7 on 2026-08-06 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_papersection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='papersection',
            new_name='papers_pape_paper_i_f98c00_idx',
            old_name='papers_paperse_paper_id_ef9774_idx',
        ),
        migrations.AddField(
            model_name='papersection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papersection',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='papersection',
            name='original_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='papersection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
