# Generated by Django 6.0.7 on 2026-08-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_rename_papers_paperse_paper_id_ef9774_idx_papers_pape_paper_i_f98c00_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersection',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
    ]
