# Generated by Django 6.0.7 on 2026-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_glossary_schema_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='importance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='paper_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='glossary',
            index=models.Index(fields=['paper', 'display_order'], name='papers_glos_paper_i_95c98a_idx'),
        ),
    ]
