# Generated by Django 6.0.7 on 2026-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_add_flashcard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
