# Generated by Django 6.0.7 on 2026-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_quizquestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivaquestion',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vivaquestion',
            name='examiner_tip',
            field=models.TextField(blank=True),
        ),
    ]
