# Generated by Django 6.0.7 on 2026-08-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_vivaquestion_category_vivaquestion_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='revision_notes',
            field=models.TextField(blank=True),
        ),
    ]
