# Generated by Django 6.0.7 on 2026-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_update_plan_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='source',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('ADMIN', 'Admin')], default='PAYMENT', max_length=20),
        ),
    ]
